/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lewis_cutajar_programming_concepts_home_assignment_swd4.pkg2b;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;


/**
 *
 * @author lewis
 */
public class Assignment_GUI_Form extends javax.swing.JFrame {

    ArrayList<String> StudentRecords = new ArrayList<>();

    /**
     * Creates new form Assignment_GUI_Form
     */
    public Assignment_GUI_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        ScrCover = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitle.setText("Student's Details");

        lblName.setText("Name");

        lblSurname.setText("Surname");

        lblAge.setText("Age");
        lblAge.setToolTipText("");

        lblDate.setText("Date (YYYY-MM-DD)");

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        ScrCover.setViewportView(txtDisplay);

        btnAdd.setText("Add Student");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnShow.setText("Show Students");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnSave.setText("Save all students to File");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrCover, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblName)
                                        .addComponent(lblSurname)
                                        .addComponent(lblAge))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtName)
                                        .addComponent(txtSurname)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(lblTitle))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblDate)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                            .addComponent(btnAdd))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnSave))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(btnShow)
                            .addGap(330, 330, 330))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(20, 20, 20)
                .addComponent(btnShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrCover, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
    }//GEN-LAST:event_txtDateActionPerformed

    /**
     * This button adds all the inputs to variables, 
     * clears the text fields and checks to make sure all inputs are 
     * valid before adding them to functions
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String inpName = txtName.getText();
        String inpSurname = txtSurname.getText();
        String inpAge = txtAge.getText();
        String inpDate = txtDate.getText();

        txtName.setText("");
        txtSurname.setText("");
        txtAge.setText("");
        txtDate.setText("");
        
        boolean valid = true;
        
        if (inpName.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Error: please input a name", "Error", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        
        if(inpSurname.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Error: please input a surname", "Error", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }
        
        if(!intValidate(inpAge)){
            valid = false;
        }
        
        if(!dateValidate(inpDate)){
            valid = false;
        }
        
        if(valid){
            String Entry = ""; 
            Entry += inpName + " " + inpSurname + " | " + "Age: " + Integer.parseInt(inpAge) + " | " + "Date: " + LocalDate.parse(inpDate);
            StudentRecords.add(Entry);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed
    
    /**
     * This method checks that the age is between 10 and 100, 
     * that the text field is not empty and also a valid integer
     */
    private boolean intValidate(String intInput){
        
        if(intInput == null || intInput.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Error: Age must be filled", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try
        {
            int ageInput = Integer.parseInt(intInput.trim());
            if (ageInput <= 10 || ageInput >= 100)
            {
                JOptionPane.showMessageDialog(null, "Error: Age must be a valid number", "Error", JOptionPane.ERROR_MESSAGE);
            }
            return true;
 
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Error: Age must be a valid number", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    /**
     * This method checks that the date was inputted in YYYY-MM-DD format into the
     * text field if it wasn't it returns an error but if it is it returns true
     * allowing the validation to pass
    */
    private boolean dateValidate(String inpDate) {
        try {
            DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
            LocalDate.parse(inpDate, format);
        
            return true;
            
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Error: Date must be in YYYY-MM-DD", "Error", JOptionPane.ERROR_MESSAGE);    
            return false;
        }   
    }
    
    /**
     * This button is calling on the method that updates the text area  
     */
    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        UpdateTaskDisplay();
    }//GEN-LAST:event_btnShowActionPerformed

    /**
     * This method updates the text area to display in information inputted by the
     * user in the style of
     * ' Name Surname | Age | Date '
     */
    private void UpdateTaskDisplay(){   
        
        String fullList = "";
        for (int i = 0; i < StudentRecords.size(); i++) {
            fullList += StudentRecords.get(i) + "\n";
        }
        txtDisplay.setText(fullList);
    }
    
    /**
     * This code saves the file under the name ' Students.txt '
     * If a file under the same name exists it deletes that file
     * and saves the new entries under the same name it saves the entries in the
     * style of ' Name Surname | Age | Date ' and tell the user ' Records saved successfully '
     * if something goes wrong during the saving of the file it gives an error saying 'Error saving to file '
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Path path = Paths.get("Students.txt");
        
        try{
            if (Files.exists(path)){
                Files.delete(path);
                System.out.println("File deleted successfully!");
            } else {
                System.out.println("File does not exist!");
            }
        } catch (IOException e){
            System.out.println("An error occured while deleting " + e.getMessage());
        }
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("Students.txt"))){
            for (int i = 0; i < StudentRecords.size(); i++){
                writer.write(StudentRecords.get(i));
                writer.newLine();
            }
            JOptionPane.showMessageDialog(null, "Records saved successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error saving to file: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment_GUI_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment_GUI_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment_GUI_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment_GUI_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment_GUI_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrCover;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtDisplay;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

    private boolean date(DateTimeFormatter format) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
